resources:
   containers:
   - container: fpkde
     options: '--privileged'
     image: mobsya/flatpak-builders:kde-latest

trigger:
  tags:
    include:
    - 2.*
  branches:
    include:
    - '*'

variables:
- group: passwords
- name: blockly_version
  value: "v20200506.1"
- name: scratch_version
  value: "v20201116.1"
- name: blockly_url
  value: "https://github.com/Mobsya/thymio-blockly-standalone/releases/download/$(blockly_version)/thymio-blockly.tar.gz"
- name: scratch_url
  value: "https://github.com/Mobsya/scratch-gui/releases/download/$(scratch_version)/scratch-gui.tar.gz"
- name: vpl3_url
  value: "https://github.com/Mobsya/ci-data/releases/download/data/vpl3-thymio-suite.tar.gz"
- name: vcpkg_commit
  value: "cccef600decd1091a20a0b4d8a2e61f7041eb686"
- name: visual_bootstrapper
  value: "https://github.com/Mobsya/ci-data/releases/download/data/vs_enterprise.exe"

jobs:
- job: 'BuildAndroid_armeabi'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      armeabi:
        TARGET_ARCH: 'armeabi-v7a'
      aarch64:
        TARGET_ARCH: 'arm64-v8a'
      x86_64:
        TARGET_ARCH: 'x86_64'
  variables:
    - name: API_LEVEL
      value: '28'
    - name: NDK_VERSION
      value: '21'
    - name: QT_VERSION
      value: '5.15.2'
  steps:
  - script: |
      docker pull mobsya/thymio-dev-env:android$API_LEVEL-ndk$NDK_VERSION-qt$QT_VERSION
    displayName: 'Pull docker image'

  - script: |
      git submodule update --init --recursive
    displayName: 'Clone submodules'

  - script: |
      mkdir $(pwd)/build $(pwd)/build/$TARGET_ARCH
      sudo docker run --rm -v $(pwd):/src:rw -v $(pwd)/build/$TARGET_ARCH:/build:rw mobsya/thymio-dev-env:android$API_LEVEL-ndk$NDK_VERSION-qt$QT_VERSION "cmake -DANDROID_NATIVE_API_LEVEL=$API_LEVEL -DANDROID_ABI=$TARGET_ARCH -DCMAKE_TOOLCHAIN_FILE=/android/ndk/android-ndk-r$NDK_VERSION/build/cmake/android.toolchain.cmake -DCMAKE_FIND_ROOT_PATH=/qt -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -GNinja -S /src -B /build && cd /build && ninja -j $(nproc)"
      cp 'build/$TARGET_ARCH/bin/thymio-launcher.apk' $(Build.ArtifactStagingDirectory)
    displayName: 'Build Thymio Suite'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'thymio-suite-android'